### ISSUE TITLE
Add labels on the user registration page 

### ISSUE THREAD

**Issue by look4parul** [Rebel-Scum-Analytical/Team-Project2#41]
Add labels at the registration page for the input fields.
1) Create User Name (e.g. not null)
2) Create Password (not null)
3) First Name 
4) Last Name
5) Gender(e.g. Select from the drop down)
6) Date of birth(YYYY-DD-MM)
7) Height (e.g. "in inches")
8) Weight(e.g. in lbs)
9) Physical activity Level (Select from the drop down)

**Comment by rando010** [comment]
I added the labels in the app.py
