### ISSUE TITLE
Update the user registration page outlook

### ISSUE THREAD

**Issue by look4parul** [Rebel-Scum-Analytical/Team-Project2#44]
The new user registration page view needs to synced with the other pages

**Comment by look4parul** [comment]
Working on the issue. FIle New_user.html needs to be uodated.

**Comment by look4parul** [comment]
Old create_user screen has been changed from img1.png to img2.png.  For details please 
![img2](https://user-images.githubusercontent.com/57111458/78384811-79fc0c80-75a0-11ea-8717-ca750c143081.PNG)
refer the files attached.
![img1](https://user-images.githubusercontent.com/57111458/78384607-1671df00-75a0-11ea-86c0-f7b278f3c40e.PNG)

**Comment by rando010** [comment]
I removed the outline from each box by combining everything into one div. now there is only one outline.
